//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int Id { get; set; }
        public System.Guid Guid { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string OfficePhone { get; set; }
        public string CellPhone { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
        public int DepartmentId { get; set; }
        public System.Guid DepartmentGuid { get; set; }
        public int JobTitleId { get; set; }
        public System.Guid JobTitleGuid { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> LastActive { get; set; }
        public Nullable<int> CreatedByStaffId { get; set; }
        public Nullable<System.Guid> CreatedByStaffGuid { get; set; }
        public Nullable<int> ModifiedByStaffId { get; set; }
        public Nullable<System.Guid> ModifiedByStaffGuid { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int AvatarId { get; set; }
        public System.Guid AvatarGuid { get; set; }
        public int PermissionId { get; set; }
        public System.Guid PermissionGuid { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual JobTitle JobTitle { get; set; }
        public virtual Staff CreatedByStaff { get; set; }
        public virtual Staff ModifiedByStaff { get; set; }
        public virtual Avatar Avatar { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
